# This is a basic workflow to help you get started with Actions

name: NGINX with modsec install to server

# Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [self-hosted, nginx]
    steps:
      - uses: actions/checkout@v4

    # Steps represent a sequence of tasks that will be executed as part of the job
      # Runs a single command using the runners shell
      - name: init check
        run: |
          ./install.sh
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo nginx started
